# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: hashicorp/terraform:light

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    terraform_deploy_dev: &terraform_deploy_dev
      run:
        name: terraform deploy dev
        command: |
          cd env/dev
          echo $DEV_AWS_ACCESS_KEY_ID
          export AWS_ACCESS_KEY_ID = $DEV_AWS_ACCESS_KEY_ID
          export AWS_SECRET_ACCESS_KEY = $DEV_AWS_SECRET_ACCESS_KEY
          terraform init
          terraform plan -out=dev.plan
          terraform apply --auto-approve

    terraform_deploy_prod: &terraform_deploy_prod
      run:
        name: terraform deploy prod
        command: |
          cd env/dev
          export AWS_ACCESS_KEY_ID = $PROD_AWS_ACCESS_KEY_ID
          export AWS_SECRET_ACCESS_KEY = $PROD_AWS_SECRET_ACCESS_KEY
          terraform init
          terraform plan -out=prod.plan
#          terraform apply --auto-approve

    steps:
      - checkout
      - *terraform_deploy_dev
      - *terraform_deploy_prod
