# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:

  terraform_deploy_dev:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          command: |
            cd env/dev
            export AWS_ACCESS_KEY_ID=$DEV_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$DEV_AWS_SECRET_ACCESS_KEY
            terraform init
            terraform plan
            terraform apply --auto-approve
  terraform_prod_plan:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          command: |
            cd env/prod
            export AWS_ACCESS_KEY_ID=$PROD_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$PROD_AWS_SECRET_ACCESS_KEY
            terraform init
            terraform plan
      - persist_to_workspace:
              root: .
              paths: env/prod

workflows:
  version: 2
  build_plan_approve_apply:
    jobs:
      - terraform_deploy_dev
      - terraform_prod_plan